name: Sync Docs to S3
on:
  push:
    branches: [main]
    paths: ['build_docs/**']
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Sync docs to S3
        run: |
          aws s3 sync docs/ s3://oscar-opensearch-kb/docs/ \
            --delete \
            --exclude "*.git*" \
            --exclude "*.DS_Store"